- name: Configure Raspberry Pi
  hosts: pi
  remote_user: pi
  become: True
  vars_files:
  - vars.yml

  tasks:
#  - name: Overclock SD
#    lineinfile:
#      dest: /boot/config.txt
#      regexp: "^dtoverlay=sdhost,overclock_50=100"
#      line: "dtoverlay=sdhost,overclock_50=100"
#      insertafter: EOF
#      state: present

  - name: Add ssh key
    authorized_key: user=pi key="{{ lookup('file', 'files/ssh_keys') }}"

  - name: Wireless config
    template: src=templates/wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf

  - name: Partition
    shell: raspi-config --expand-rootfs

  - name: restart machine
    shell: shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=4 timeout=60
    become: false
