- name: Install retropie
  hosts: pi
  remote_user: pi
  become: True
  tasks:
    - name: upgrade packages
      apt: upgrade=dist update_cache=yes

    - name: install requirements
      apt: pkg=git state=installed

    - name: Git clone Retro-Pie
      git: repo=https://github.com/RetroPie/RetroPie-Setup.git depth=1 dest=/home/pi/RetroPie-Setup version=master

    - name: Install and configure EmulationStation
      command: "{{item}} chdir=/home/pi/RetroPie-Setup"
      with_items:
          - ./retropie_packages.sh emulationstation depends
          - ./retropie_packages.sh emulationstation install_bin
          - ./retropie_packages.sh emulationstation configure
          - ./retropie_packages.sh esthemes install_theme
          - ./retropie_packages.sh autostart enable
      tags: debug

    - name: Install and configure runcommand
      command: "{{item}} chdir=/home/pi/RetroPie-Setup"
      with_items:
          - ./retropie_packages.sh runcommand depends
          - ./retropie_packages.sh runcommand install

    - name: Install and configure retroarch and some cores
      shell: >
          ./retropie_packages.sh {{item}} depends;
          ./retropie_packages.sh {{item}} install_bin;
          ./retropie_packages.sh {{item}} configure
      args:
          chdir: "/home/pi/RetroPie-Setup"
      with_items:
          - retroarch
          - lr-fceumm
          - lr-snes9x2002
          - lr-picodrive
          - lr-mupen64plus
          - lr-pcsx-rearmed

    - name: Setup splash screen
      shell: >
          ./retropie_packages.sh {{item}} depends;
          ./retropie_packages.sh {{item}} install_bin;
          ./retropie_packages.sh {{item}} download_extra;
          echo "/home/pi/RetroPie/splashscreens/retropie-extra/dalecoop-snes-controller.jpg" > /etc/splashscreen.list;
          ./retropie_packages.sh {{item}} enable;
      args:
          chdir: "/home/pi/RetroPie-Setup"
      with_items:
          - splashscreen

    - name: copy gamepad config
      copy: src=files/{{ item }} dest=/opt/retropie/configs/all/retroarch-joypads
      with_items:
          - 8BitPro.cfg
          - LogitechGamepadF310.cfg

    - name: copy gamepad config for emulationstation
      copy: src=files/emulationstation/{{ item }} dest=/opt/retropie/configs/all/emulationstation/
      with_items:
        - es_settings.cfg
        - es_input.cfg
